try {
    const a=20;
    a=12;
    
}
catch(err){
    console.log(err)
}